---
# 1) Optional pre-tasks: install containerd on every node
- name: Prepare Rocky 9 nodes
  hosts: k8s_nodes
  become: true
  tasks:
    - name: Install container runtime
      import_role:
        name: geerlingguy.containerd

# 2) Run the Kubespray cluster playbook that lives inside the collection
- name: Deploy the Kubernetes cluster with Kubespray
  import_playbook: kubernetes_sigs.kubespray.cluster
