---
# This playbook first ensures necessary host-level prerequisites are met,
# and then imports the main Kubespray cluster deployment playbook.

- name: Ensure /hostbin directory exists and has correct permissions
  hosts: all # This targets all hosts in your inventory (master and worker)
  become: true # Ensures tasks run with root privileges
  tasks:
    - name: Create /hostbin if it doesn't exist and set appropriate permissions
      ansible.builtin.file:
        path: /hostbin
        state: directory # Ensures the path is a directory, creating it if it doesn't exist
        owner: root      # Sets the owner to root
        group: root      # Sets the group to root
        mode: '0755'     # Sets permissions to rwxr-xr-x (root can read/write/execute, others can read/execute)
      # This condition ensures the task only runs on RedHat-based systems (like Rocky Linux)
      when: ansible_os_family == "RedHat"
      # The 'always' tag ensures this task runs even if specific tags are used for the playbook,
      # which is important for critical prerequisites.
      tags: always

# This play imports the main Kubespray cluster deployment playbook.
# It will run after the prerequisite tasks in the first play are completed.
- import_playbook: kubernetes_sigs.kubespray.cluster