---
- name: Install/upgrade jmespath on the control host
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure jmespath is present
      pip:
        name: jmespath
        state: present
