---
# Galaxy / Automation-Hub dependencies for this project
collections:
  # Core Kubernetes modules – comes from Galaxy
  - name: kubernetes.core
    version: "2.4.0"

  # Kubespray straight from its Git repo (← THIS line changed)
  - source: git+https://github.com/kubernetes-sigs/kubespray.git
    type: git
    version: v2.28.0        # pin a tag; update as needed

roles:
  - name: geerlingguy.containerd
    version: "1.2.0"
